name       : kpat
version    : 20.04.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kpat-20.04.0.tar.xz : f5aced42e9521923d8b63df6e3cf577faba4efab27d2dc37b70e320e1d13c4e5
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
libsplit   : no
summary    : KDE patience game
description: |
    KDE patience game.
builddeps  :
    - pkgconfig(libfreecell-solver)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
#check      : |
    # Tests look for kpat binary in the wrong dir. Patch needed
    #%ninja_check
