name       : kpat
version    : 23.04.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kpat-23.04.3.tar.xz : 74aea1d6de8f261b97b018506920e8809534e1331b44e2657e9ab60df6268395
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
summary    : KDE patience game
description: |
    KDE patience game.
libsplit   : no
builddeps  :
    - pkgconfig(libblack-hole-solver)
    - pkgconfig(libfreecell-solver)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - knewstuff-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
