name       : kpat
version    : 21.12.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kpat-21.12.0.tar.xz : e24f697a6cdba583c4628f39571b477160686236bb89e6a615653f45f96e4a0c
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
summary    : KDE patience game
description: |
    KDE patience game.
libsplit   : no
builddeps  :
    - pkgconfig(libblack-hole-solver)
    - pkgconfig(libfreecell-solver)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - knewstuff-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
