name       : kpat
version    : 23.04.1
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kpat-23.04.1.tar.xz : 650f21b43b3b27dcaa8684dfd4cca09485cfcce65b0f444871e4c782e3cbc180
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
summary    : KDE patience game
description: |
    KDE patience game.
libsplit   : no
builddeps  :
    - pkgconfig(libblack-hole-solver)
    - pkgconfig(libfreecell-solver)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - knewstuff-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
