name       : kpat
version    : 20.12.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kpat-20.12.2.tar.xz : dd7a168ed23410d9306a24fc0b80c037764be39e70a635477f8c2fa506199bbd
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
summary    : KDE patience game
description: |
    KDE patience game.
libsplit   : no
builddeps  :
    - pkgconfig(libblack-hole-solver)
    - pkgconfig(libfreecell-solver)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - knewstuff-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
