name       : kpat
version    : 21.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kpat-21.04.2.tar.xz : fdd19a5047b3ab12a36f121c66a7b854f5b1696f8626350f2a4a4d2094dc2151
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
homepage   : https://kde.org/applications/games/org.kde.kpat
component  : games.card
summary    : KDE patience game
description: |
    KDE patience game.
libsplit   : no
builddeps  :
    - pkgconfig(libblack-hole-solver)
    - pkgconfig(libfreecell-solver)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - knewstuff-devel
    - libkdegames-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
