name       : kpat
version    : 17.12.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kpat-17.12.3.tar.xz : 902b040b220d8d41711e6eb264fdd7bdaecaaa9678eadc8faa64469bbb75785a
license    :
    - GFDL-1.2
    - GPL-2.0
component  : games.card
optimize   : lto
libsplit   : no
summary    : KDE patience game
description: |
    KDE patience game.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - libkdegames-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
